### ISSUE TITLE
Support creating new configuration files based on Cryosat-2 configuration template

### ISSUE THREAD

**Issue by hans-permana** [DeDop/dedop-studio#6]
DeDop Studio shall support a new feature at the DeDop Core that provides an additional parameter `--cryosat-adapted` when creating new configuration files, to generate configurations based on Cryosat-2 configuration templates. [This](https://github.com/DeDop/dedop-core/issues/41) is the description of the modifications at DeDop Core. 

At the `Add a new configuration file` dialog, add a new drop-down list consisting `Cryosat-2 FBR` and `Sentinel-3`. When `Cryosat-2 FBR` is selected, parameter `--cryosat-adapted` will be included when sending a webapi call to create a new configuration.

**Comment by hans-permana** [comment]
@mark-ep , is it ok to use `Cryosat-2 FBR` and `Sentinel-3` as the displayed name or should I use something else?

**Comment by mark-ep** [comment]
I would recommend using `Adapted Cryosat-2 FBR`, or simply `Adapted Cryosat`. We need to be clear that DeDop *does not* read standard Cryosat FBR data.

**Comment by hans-permana** [comment]
Understood, I will use `Adapted Cryosat-2 FBR` and `Sentinel-3` as the drop-down list options. Thank you.
